function ColorMyPencils(color)
	color = color or "gruber-darker"
	vim.cmd.colorscheme(color)
  vim.o.termguicolors = true
  vim.cmd([[highlight Typedef guifg=#d4e5fg]])
  vim.cmd([[highlight TreesitterContext guibg=#2c2c2c]])
  -- vim.cmd([[highlight Normal guibg=#202020 ctermbg=NONE]])
  -- vim.cmd([[highlight LineNr guibg=NONE]])
  -- vim.cmd([[highlight SignColumn guibg=NONE]])
  -- vim.cmd([[highlight DiagnosticVirtualTextError guibg=#26292c]])
  -- vim.cmd([[highlight DiagnosticVirtualTextHint guibg=#26292c]])
  -- vim.cmd([[highlight DiagnosticVirtualTextInfo guibg=#26292c]])
  -- vim.cmd([[highlight DiagnosticVirtualTextOk guibg=#26292c]])
  -- vim.cmd([[highlight DiagnosticVirtualTextWarn guibg=#26292c]])
  -- vim.cmd([[highlight IndentBlanklineChar guifg=#282828]])
  -- vim.cmd([[highlight BufferTabpageFill guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultCurrent guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultCurrentMod guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultCurrentSign guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultCurrentSignRight guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultCurrentIcon guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultCurrentERROR guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultCurrentHINT guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultCurrentINFO guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultCurrentWARN guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultCurrentIcon guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultVisible guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultVisibleMod guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultVisibleSign guibg=NONE]])
  -- vim.cmd([[highlight BufferDefaultVisibleSignRight guibg=NONE]])
end

ColorMyPencils()
